apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-test-01
  description: This is some component
  tags:
    - java
    - data
spec:
  type: service
  lifecycle: experimental
  owner: team-a
#   system: artist-engagement-portal
